### ISSUE TITLE
Feature Request: Dummy Replay Saving

### ISSUE THREAD

**Issue by camji** [Nullctipus/IdolShowdownTrainingPlusPlus#1]
You should be able to output Dummy replays to a file and be able to replay them. Much like [Under Night In-Birth Replay Editor](https://github.com/Labreezy/UnistRecordingEditor/releases/tag/0.0.2). It would make working labbing so much easier.

**Comment by Nullctipus** [comment]
Implemented basic system in latest release

**Comment by camji** [comment]
Wow... Thank you so much. Can't put it into words really, I'll try it out
