### ISSUE TITLE
Possible enhancements to #1 (and a bug)

### ISSUE THREAD

**Issue by camji** [Nullctipus/IdolShowdownTrainingPlusPlus#3]
- Make a toggle to reverse inputs
This will make it easier to actually implement the replays as you have to usually input them as player 2, for now though, we can just use 8R and then do the recording 

- Control Which Player the Replay plays as.
When you try to play the replay during a recording, The recording keeps controlling the player character and only the player character, not the dummy. Which can be pretty useful, but the point of replay editor is to edit the dummy replay and not only the player character, so some kind of fix or workaround is in order, I guess.

- The usual Keybind stuff
As per usual and something you probably heard tens of times while making mods, attach a keybind to the replay of the selected replay. Make sure there's a keybind for Reloading the set replay and playing the set replay because it's going to be more popular to have the replay editing up on a seperate window

**Comment by Nullctipus** [comment]
Added to latest release
