### ISSUE TITLE
Enhancements: After Block

### ISSUE THREAD

**Issue by camji** [Nullctipus/IdolShowdownTrainingPlusPlus#6]
Wow, didn't expect it to be that quick, I won't assume it was easy, here are just some QOL things that you can maybe ignore

- Toggle which side does the input after blocking
     This is to prevent the player from doing the recording when testing a situation that requires them to block
     
- Add an option for "After Teching"
     I expect this one to actually be difficult to do, as you would have to override the current dummy, or manually make the dummy tech yourself. 
     
     The easiest way to use the recording feature as of now is to set the Dummy Playback Setting to "Play after damage taken" on a null demo and then do everything. Hopefully, there is some kind of workaround you can use to allow usage in normal Dummy Settings. If so, then it'd be nearly complete.

**Comment by Nullctipus** [comment]
Semi-Added to Latest Release
